#!/bin/sh
#APP_VERSION=1.0
#wget http://repository.example.com/app/app-$APP_VERSION.jar -O app.jar
MAVEN_VERSION=3.5.4
#wget https://repo1.maven.org/maven2/org/apache/maven/apache-maven/$MAVEN_VERSION/apache-maven-$MAVEN_VERSION-bin.zip
echo 'Hello dude.. https://repo1.maven.org/maven2/org/apache/maven/apache-maven/$MAVEN_VERSION/apache-maven-$MAVEN_VERSION-bin.zip'